# permissions for end users to edit namespacemanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-operator
    app.kubernetes.io/managed-by: kustomize
  name: namespacemanagement-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - namespacemanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - namespacemanagements/status
  verbs:
  - get
