apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  namespaceManagement:
    - name: tenant-ns # allow a single namespace
      allowManagedBy: true
